import unittest

from customer_api.app import create_app
from customer_api.config import ApiSettings


class ServerRouteInventoryTests(unittest.TestCase):
    def test_all_public_api_routes_are_registered_after_modularization(self):
        app = create_app(settings=ApiSettings(), data_source=object())
        actual = {
            (method, route.path)
            for route in app.routes
            for method in (getattr(route, "methods", None) or ())
            if route.path == "/health" or route.path.startswith("/api/v1/")
        }
        expected = {
            ("GET", "/health"),
            ("POST", "/api/v1/auth/login"),
            ("POST", "/api/v1/auth/logout"),
            ("GET", "/api/v1/auth/me"),
            ("PUT", "/api/v1/auth/password"),
            ("GET", "/api/v1/records"),
            ("GET", "/api/v1/records/{record_id}"),
            ("POST", "/api/v1/records"),
            ("PUT", "/api/v1/records/{record_id}"),
            ("PUT", "/api/v1/records/{record_id}/with-history"),
            ("DELETE", "/api/v1/records/{record_id}"),
            ("POST", "/api/v1/imports/records"),
            ("GET", "/api/v1/records/{record_id}/contact-logs"),
            ("POST", "/api/v1/records/{record_id}/contact-logs"),
            ("DELETE", "/api/v1/records/{record_id}/contact-logs/{log_id}"),
            ("GET", "/api/v1/records/{record_id}/owner-contacts"),
            ("POST", "/api/v1/records/{record_id}/owner-contacts"),
            ("POST", "/api/v1/records/{record_id}/owner-contacts/link"),
            ("GET", "/api/v1/records/{record_id}/owner-contacts/{relation_id}"),
            ("PUT", "/api/v1/records/{record_id}/owner-contacts/{relation_id}"),
            (
                "POST",
                "/api/v1/records/{record_id}/owner-contacts/{relation_id}/deactivate",
            ),
            (
                "POST",
                "/api/v1/records/{record_id}/owner-contacts/{relation_id}/reactivate",
            ),
            ("GET", "/api/v1/owner-contacts/search"),
            ("GET", "/api/v1/owner-contacts/duplicates"),
            ("GET", "/api/v1/contacts/search"),
            ("POST", "/api/v1/contacts/duplicate-check"),
            ("GET", "/api/v1/owners/{owner_id}/contacts"),
            ("POST", "/api/v1/owners/{owner_id}/contacts"),
            ("POST", "/api/v1/owners/{owner_id}/contacts/link"),
            ("GET", "/api/v1/owners/{owner_id}/contacts/{relation_id}"),
            ("PUT", "/api/v1/owners/{owner_id}/contacts/{relation_id}"),
            (
                "POST",
                "/api/v1/owners/{owner_id}/contacts/{relation_id}/deactivate",
            ),
            (
                "POST",
                "/api/v1/owners/{owner_id}/contacts/{relation_id}/reactivate",
            ),
            ("GET", "/api/v1/records/{record_id}/follow-up"),
            ("PUT", "/api/v1/records/{record_id}/follow-up"),
            ("DELETE", "/api/v1/records/{record_id}/follow-up"),
            ("GET", "/api/v1/follow-ups"),
            ("GET", "/api/v1/projects"),
            ("POST", "/api/v1/projects"),
            ("PUT", "/api/v1/projects/{project_id}"),
            ("DELETE", "/api/v1/projects/{project_id}"),
            ("PUT", "/api/v1/projects/{project_id}/records"),
            ("PUT", "/api/v1/projects/{project_id}/archive"),
            ("GET", "/api/v1/project-tasks"),
            ("POST", "/api/v1/project-tasks"),
            ("PUT", "/api/v1/project-tasks/{task_id}"),
            ("DELETE", "/api/v1/project-tasks/{task_id}"),
            ("GET", "/api/v1/tags"),
            ("POST", "/api/v1/tags"),
            ("PUT", "/api/v1/tags/assignments"),
            ("PUT", "/api/v1/tags/{tag_id}"),
            ("DELETE", "/api/v1/tags/{tag_id}"),
            ("GET", "/api/v1/records/{record_id}/tags"),
            ("PUT", "/api/v1/records/{record_id}/tags"),
            ("GET", "/api/v1/records/{record_id}/attachments"),
            ("POST", "/api/v1/records/{record_id}/attachments"),
            ("POST", "/api/v1/records/{record_id}/attachments/upload"),
            ("GET", "/api/v1/records/{record_id}/attachments/{attachment_id}/content"),
            ("GET", "/api/v1/records/{record_id}/attachments/{attachment_id}/thumbnail"),
            ("PATCH", "/api/v1/records/{record_id}/attachments/{attachment_id}"),
            ("DELETE", "/api/v1/records/{record_id}/attachments/{attachment_id}"),
            ("GET", "/api/v1/owners"),
            ("GET", "/api/v1/lands"),
            ("GET", "/api/v1/records/{record_id}/change-logs"),
            ("POST", "/api/v1/record-change-logs"),
            ("GET", "/api/v1/custom-fields"),
            ("POST", "/api/v1/custom-fields"),
            ("PUT", "/api/v1/custom-fields/{field_id}"),
            ("DELETE", "/api/v1/custom-fields/{field_id}"),
            ("GET", "/api/v1/records/{record_id}/custom-values"),
            ("PUT", "/api/v1/records/{record_id}/custom-values"),
            ("PUT", "/api/v1/custom-values/assignments"),
            ("GET", "/api/v1/text-templates"),
            ("POST", "/api/v1/text-templates"),
            ("PUT", "/api/v1/text-templates/{template_id}"),
            ("DELETE", "/api/v1/text-templates/{template_id}"),
            ("GET", "/api/v1/watchlist"),
            ("PUT", "/api/v1/watchlist"),
            ("GET", "/api/v1/operation-logs"),
            ("POST", "/api/v1/operation-logs"),
            ("GET", "/api/v1/record-locations"),
            ("PUT", "/api/v1/records/{record_id}/location"),
            ("GET", "/api/v1/field-visits/today"),
            ("POST", "/api/v1/field-visits"),
            ("GET", "/api/v1/field-visits/{route_id}"),
            ("POST", "/api/v1/field-visits/{route_id}/items"),
            ("POST", "/api/v1/field-visits/{route_id}/optimize/preview"),
            ("POST", "/api/v1/field-visits/{route_id}/optimize"),
            ("POST", "/api/v1/field-visits/{route_id}/reorder"),
            ("PATCH", "/api/v1/field-visit-items/{item_id}"),
            ("POST", "/api/v1/field-visit-items/{item_id}/cancel"),
            ("POST", "/api/v1/field-visit-items/{item_id}/restore"),
            ("POST", "/api/v1/field-visit-items/{item_id}/start"),
            ("POST", "/api/v1/field-visit-items/{item_id}/complete"),
            ("POST", "/api/v1/field-visit-items/{item_id}/skip"),
            ("POST", "/api/v1/field-visit-items/{item_id}/postpone"),
            ("GET", "/api/v1/duplicate-reviews"),
            ("POST", "/api/v1/duplicate-reviews"),
            ("POST", "/api/v1/attachments/verify"),
            ("GET", "/api/v1/recycle-bin"),
            ("POST", "/api/v1/recycle-bin/restore"),
            ("POST", "/api/v1/recycle-bin/purge"),
            ("GET", "/api/v1/undo-operations"),
            ("POST", "/api/v1/undo-operations/snapshot"),
            ("POST", "/api/v1/undo-operations/insert"),
            ("POST", "/api/v1/undo-operations/{operation_id}/apply"),
            ("POST", "/api/v1/records/merge"),
            ("POST", "/api/v1/notifications/refresh"),
            ("GET", "/api/v1/notifications"),
            ("PUT", "/api/v1/notifications"),
            ("GET", "/api/v1/users"),
            ("POST", "/api/v1/users"),
            ("PUT", "/api/v1/users/{user_id}"),
            ("PUT", "/api/v1/users/{user_id}/password"),
            ("POST", "/api/v1/maintenance/encrypt-existing-records"),
            ("GET", "/api/v1/server-backups/status"),
            ("GET", "/api/v1/server-backups"),
            ("POST", "/api/v1/server-backups"),
            ("POST", "/api/v1/server-backups/maintenance"),
            ("POST", "/api/v1/server-backups/restore"),
            ("GET", "/api/v1/server-backup-targets"),
            ("POST", "/api/v1/server-backup-targets"),
            ("PUT", "/api/v1/server-backup-targets/{target_id}"),
            ("DELETE", "/api/v1/server-backup-targets/{target_id}"),
            ("POST", "/api/v1/server-backup-targets/sync"),
        }
        self.assertEqual(actual, expected)
