-- PostgreSQL schema for the self-hosted Windows/iPhone system.
-- Sensitive owner values keep the existing enc:v1: Fernet ciphertext format.

CREATE TABLE IF NOT EXISTS schema_migrations (
    version INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO schema_migrations (version, name)
VALUES (1, 'normalized owners lands ownerships and mobile API')
ON CONFLICT (version) DO NOTHING;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    display_name TEXT,
    role TEXT NOT NULL DEFAULT 'viewer' CHECK (role IN ('admin', 'editor', 'viewer')),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    password_salt TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    encryption_salt TEXT NOT NULL,
    wrapped_data_key TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS app_settings (
    setting_key TEXT PRIMARY KEY,
    setting_value TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS owners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_key TEXT NOT NULL UNIQUE,
    owner_name TEXT NOT NULL,
    external_id TEXT,
    address TEXT,
    phone TEXT,
    category TEXT,
    development_status TEXT,
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    land_key TEXT NOT NULL UNIQUE,
    district TEXT NOT NULL DEFAULT '',
    section TEXT NOT NULL DEFAULT '',
    land_number TEXT NOT NULL DEFAULT '',
    area TEXT,
    declared_value TEXT,
    zoning TEXT,
    location_note TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (district, section, land_number)
);

CREATE TABLE IF NOT EXISTS ownerships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_customer_id BIGINT UNIQUE,
    owner_id BIGINT NOT NULL REFERENCES owners(id) ON DELETE RESTRICT,
    land_id BIGINT NOT NULL REFERENCES lands(id) ON DELETE RESTRICT,
    registration_order TEXT,
    numerator TEXT,
    denominator TEXT,
    ping TEXT,
    total_declared_value TEXT,
    registration_reason TEXT,
    note TEXT,
    visit_log TEXT,
    name TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ownerships_owner_id ON ownerships(owner_id);
CREATE INDEX IF NOT EXISTS idx_ownerships_land_id ON ownerships(land_id);
CREATE INDEX IF NOT EXISTS idx_lands_location ON lands(district, section, land_number);

CREATE TABLE IF NOT EXISTS contact_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_contact_log_id BIGINT UNIQUE,
    ownership_id BIGINT NOT NULL REFERENCES ownerships(id) ON DELETE CASCADE,
    contact_date DATE,
    method TEXT,
    result TEXT,
    next_follow_up DATE,
    note TEXT,
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_contact_logs_ownership
ON contact_logs(ownership_id, contact_date DESC, id DESC);

CREATE TABLE IF NOT EXISTS follow_up_reminders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ownership_id BIGINT NOT NULL UNIQUE REFERENCES ownerships(id) ON DELETE CASCADE,
    due_date DATE,
    status TEXT NOT NULL DEFAULT '未處理',
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT '進行中',
    assigned_to BIGINT REFERENCES users(id) ON DELETE SET NULL,
    due_date DATE,
    priority TEXT NOT NULL DEFAULT '一般',
    next_action TEXT,
    estimated_area NUMERIC,
    estimated_value NUMERIC,
    note TEXT,
    archived_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS project_owners (
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    owner_id BIGINT NOT NULL REFERENCES owners(id) ON DELETE CASCADE,
    PRIMARY KEY (project_id, owner_id)
);

CREATE TABLE IF NOT EXISTS project_lands (
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    land_id BIGINT NOT NULL REFERENCES lands(id) ON DELETE CASCADE,
    PRIMARY KEY (project_id, land_id)
);

CREATE TABLE IF NOT EXISTS import_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_file_name TEXT NOT NULL,
    total_rows INTEGER NOT NULL DEFAULT 0,
    success_rows INTEGER NOT NULL DEFAULT 0,
    duplicate_rows INTEGER NOT NULL DEFAULT 0,
    failed_rows INTEGER NOT NULL DEFAULT 0,
    imported_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS import_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL REFERENCES import_batches(id) ON DELETE CASCADE,
    row_number INTEGER NOT NULL,
    raw_values JSONB NOT NULL,
    processing_status TEXT NOT NULL DEFAULT 'pending',
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (batch_id, row_number)
);

CREATE TABLE IF NOT EXISTS attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT REFERENCES owners(id) ON DELETE CASCADE,
    land_id BIGINT REFERENCES lands(id) ON DELETE CASCADE,
    project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
    storage_path TEXT NOT NULL,
    original_name TEXT NOT NULL,
    media_type TEXT,
    size_bytes BIGINT,
    sha256 TEXT,
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (owner_id IS NOT NULL OR land_id IS NOT NULL OR project_id IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    actor TEXT,
    action_type TEXT NOT NULL,
    entity_type TEXT,
    entity_id BIGINT,
    summary TEXT NOT NULL,
    detail JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Version 2: mirror the remaining desktop productivity data while keeping
-- machine-specific UI state and backup destinations local to each computer.

ALTER TABLE projects ADD COLUMN IF NOT EXISTS legacy_case_id BIGINT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS assigned_to_text TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS idx_projects_legacy_case_id
ON projects(legacy_case_id);

CREATE TABLE IF NOT EXISTS project_ownerships (
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    ownership_id BIGINT NOT NULL REFERENCES ownerships(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (project_id, ownership_id)
);

CREATE TABLE IF NOT EXISTS project_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_task_id BIGINT UNIQUE,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    assignee TEXT,
    due_date DATE,
    status TEXT NOT NULL DEFAULT '待處理',
    priority TEXT NOT NULL DEFAULT '一般',
    checklist TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_project_tasks_project
ON project_tasks(project_id, status, due_date);

CREATE TABLE IF NOT EXISTS tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_tag_id BIGINT UNIQUE,
    name TEXT NOT NULL UNIQUE,
    color TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ownership_tags (
    ownership_id BIGINT NOT NULL REFERENCES ownerships(id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ownership_id, tag_id)
);

CREATE TABLE IF NOT EXISTS custom_fields (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_field_id BIGINT UNIQUE,
    field_key TEXT NOT NULL UNIQUE,
    label TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ownership_custom_values (
    ownership_id BIGINT NOT NULL REFERENCES ownerships(id) ON DELETE CASCADE,
    field_id BIGINT NOT NULL REFERENCES custom_fields(id) ON DELETE CASCADE,
    value TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ownership_id, field_id)
);

ALTER TABLE attachments ADD COLUMN IF NOT EXISTS legacy_attachment_id BIGINT;
ALTER TABLE attachments ADD COLUMN IF NOT EXISTS ownership_id BIGINT REFERENCES ownerships(id) ON DELETE CASCADE;
ALTER TABLE attachments ADD COLUMN IF NOT EXISTS file_path TEXT;
ALTER TABLE attachments ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE attachments ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'external';
ALTER TABLE attachments ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1;
CREATE UNIQUE INDEX IF NOT EXISTS idx_attachments_legacy_attachment_id
ON attachments(legacy_attachment_id);
CREATE INDEX IF NOT EXISTS idx_attachments_ownership_id
ON attachments(ownership_id);

CREATE TABLE IF NOT EXISTS ownership_locations (
    ownership_id BIGINT PRIMARY KEY REFERENCES ownerships(id) ON DELETE CASCADE,
    latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90 AND 90),
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180 AND 180),
    source TEXT NOT NULL DEFAULT 'manual',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS duplicate_reviews (
    left_ownership_id BIGINT NOT NULL REFERENCES ownerships(id) ON DELETE CASCADE,
    right_ownership_id BIGINT NOT NULL REFERENCES ownerships(id) ON DELETE CASCADE,
    decision TEXT NOT NULL DEFAULT 'ignored',
    reviewed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (left_ownership_id, right_ownership_id),
    CHECK (left_ownership_id < right_ownership_id)
);

CREATE TABLE IF NOT EXISTS record_change_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_change_log_id BIGINT UNIQUE,
    ownership_id BIGINT NOT NULL REFERENCES ownerships(id) ON DELETE CASCADE,
    action_type TEXT NOT NULL,
    field_key TEXT NOT NULL,
    field_label TEXT NOT NULL,
    old_value TEXT,
    new_value TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS text_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_template_id BIGINT UNIQUE,
    template_type TEXT NOT NULL DEFAULT 'note',
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS recycle_bin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_recycle_id BIGINT UNIQUE,
    entity_type TEXT NOT NULL DEFAULT 'customer',
    original_id BIGINT,
    display_label TEXT,
    payload_json JSONB NOT NULL,
    deleted_by TEXT,
    deleted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS undo_operations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_undo_id BIGINT UNIQUE,
    operation_type TEXT NOT NULL,
    summary TEXT NOT NULL,
    payload_json JSONB NOT NULL,
    actor_username TEXT,
    status TEXT NOT NULL DEFAULT 'available',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    undone_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_notification_id BIGINT UNIQUE,
    notification_key TEXT NOT NULL UNIQUE,
    category TEXT NOT NULL,
    title TEXT NOT NULL,
    detail TEXT,
    severity TEXT NOT NULL DEFAULT '提醒',
    related_type TEXT,
    related_id BIGINT,
    legacy_related_id BIGINT,
    read_at TIMESTAMPTZ,
    dismissed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS import_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_profile_id BIGINT UNIQUE,
    name TEXT NOT NULL UNIQUE,
    mapping_json JSONB NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS report_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_report_template_id BIGINT UNIQUE,
    name TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    fields_json JSONB NOT NULL,
    header_text TEXT,
    footer_text TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS watchlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_watchlist_id BIGINT UNIQUE,
    name TEXT NOT NULL,
    normalized_name TEXT NOT NULL UNIQUE,
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS operation_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_operation_log_id BIGINT UNIQUE,
    action_type TEXT NOT NULL,
    summary TEXT NOT NULL,
    detail TEXT,
    actor_username TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO schema_migrations (version, name)
VALUES (2, 'desktop productivity mirror and complete parallel migration')
ON CONFLICT (version) DO NOTHING;

-- Version 3: server-owned offsite backup destinations.  Unlike desktop UI
-- preferences, these paths are resolved on the home server and shared by all
-- administrator clients.

CREATE TABLE IF NOT EXISTS server_backup_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    directory_path TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_success_at TIMESTAMPTZ,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO schema_migrations (version, name)
VALUES (3, 'server backup targets and remote maintenance')
ON CONFLICT (version) DO NOTHING;
