-- PostgreSQL schema for the self-hosted Windows/iPhone system.
-- Sensitive owner values keep the existing enc:v1: Fernet ciphertext format.

CREATE TABLE IF NOT EXISTS schema_migrations (
    version INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO schema_migrations (version, name)
VALUES (1, 'normalized owners lands ownerships and mobile API')
ON CONFLICT (version) DO NOTHING;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    display_name TEXT,
    role TEXT NOT NULL DEFAULT 'viewer' CHECK (role IN ('admin', 'editor', 'viewer')),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    password_salt TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    encryption_salt TEXT NOT NULL,
    wrapped_data_key TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS app_settings (
    setting_key TEXT PRIMARY KEY,
    setting_value TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS owners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_key TEXT NOT NULL UNIQUE,
    owner_name TEXT NOT NULL,
    external_id TEXT,
    address TEXT,
    phone TEXT,
    category TEXT,
    development_status TEXT,
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    land_key TEXT NOT NULL UNIQUE,
    district TEXT NOT NULL DEFAULT '',
    section TEXT NOT NULL DEFAULT '',
    land_number TEXT NOT NULL DEFAULT '',
    area TEXT,
    declared_value TEXT,
    zoning TEXT,
    location_note TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (district, section, land_number)
);

CREATE TABLE IF NOT EXISTS ownerships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_customer_id BIGINT UNIQUE,
    owner_id BIGINT NOT NULL REFERENCES owners(id) ON DELETE RESTRICT,
    land_id BIGINT NOT NULL REFERENCES lands(id) ON DELETE RESTRICT,
    registration_order TEXT,
    numerator TEXT,
    denominator TEXT,
    ping TEXT,
    total_declared_value TEXT,
    registration_reason TEXT,
    note TEXT,
    visit_log TEXT,
    name TEXT,
    owner_name_override TEXT,
    external_id_override TEXT,
    address_override TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ownerships_owner_id ON ownerships(owner_id);
CREATE INDEX IF NOT EXISTS idx_ownerships_land_id ON ownerships(land_id);
CREATE INDEX IF NOT EXISTS idx_lands_location ON lands(district, section, land_number);

CREATE TABLE IF NOT EXISTS contact_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_contact_log_id BIGINT UNIQUE,
    ownership_id BIGINT NOT NULL REFERENCES ownerships(id) ON DELETE CASCADE,
    contact_date DATE,
    method TEXT,
    result TEXT,
    next_follow_up DATE,
    note TEXT,
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_contact_logs_ownership
ON contact_logs(ownership_id, contact_date DESC, id DESC);

CREATE TABLE IF NOT EXISTS follow_up_reminders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ownership_id BIGINT NOT NULL UNIQUE REFERENCES ownerships(id) ON DELETE CASCADE,
    due_date DATE,
    status TEXT NOT NULL DEFAULT '未處理',
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT '進行中',
    assigned_to BIGINT REFERENCES users(id) ON DELETE SET NULL,
    due_date DATE,
    priority TEXT NOT NULL DEFAULT '一般',
    next_action TEXT,
    estimated_area NUMERIC,
    estimated_value NUMERIC,
    note TEXT,
    archived_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS project_owners (
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    owner_id BIGINT NOT NULL REFERENCES owners(id) ON DELETE CASCADE,
    PRIMARY KEY (project_id, owner_id)
);

CREATE TABLE IF NOT EXISTS project_lands (
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    land_id BIGINT NOT NULL REFERENCES lands(id) ON DELETE CASCADE,
    PRIMARY KEY (project_id, land_id)
);

CREATE TABLE IF NOT EXISTS import_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_file_name TEXT NOT NULL,
    total_rows INTEGER NOT NULL DEFAULT 0,
    success_rows INTEGER NOT NULL DEFAULT 0,
    duplicate_rows INTEGER NOT NULL DEFAULT 0,
    failed_rows INTEGER NOT NULL DEFAULT 0,
    imported_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS import_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL REFERENCES import_batches(id) ON DELETE CASCADE,
    row_number INTEGER NOT NULL,
    raw_values JSONB NOT NULL,
    processing_status TEXT NOT NULL DEFAULT 'pending',
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (batch_id, row_number)
);

CREATE TABLE IF NOT EXISTS attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT REFERENCES owners(id) ON DELETE CASCADE,
    land_id BIGINT REFERENCES lands(id) ON DELETE CASCADE,
    project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
    storage_path TEXT NOT NULL,
    original_name TEXT NOT NULL,
    media_type TEXT,
    size_bytes BIGINT,
    sha256 TEXT,
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (owner_id IS NOT NULL OR land_id IS NOT NULL OR project_id IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    actor TEXT,
    action_type TEXT NOT NULL,
    entity_type TEXT,
    entity_id BIGINT,
    summary TEXT NOT NULL,
    detail JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Version 2: mirror the remaining desktop productivity data while keeping
-- machine-specific UI state and backup destinations local to each computer.

ALTER TABLE projects ADD COLUMN IF NOT EXISTS legacy_case_id BIGINT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS assigned_to_text TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS idx_projects_legacy_case_id
ON projects(legacy_case_id);

CREATE TABLE IF NOT EXISTS project_ownerships (
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    ownership_id BIGINT NOT NULL REFERENCES ownerships(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (project_id, ownership_id)
);

CREATE TABLE IF NOT EXISTS project_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_task_id BIGINT UNIQUE,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    assignee TEXT,
    due_date DATE,
    status TEXT NOT NULL DEFAULT '待處理',
    priority TEXT NOT NULL DEFAULT '一般',
    checklist TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_project_tasks_project
ON project_tasks(project_id, status, due_date);

CREATE TABLE IF NOT EXISTS tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_tag_id BIGINT UNIQUE,
    name TEXT NOT NULL UNIQUE,
    color TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ownership_tags (
    ownership_id BIGINT NOT NULL REFERENCES ownerships(id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ownership_id, tag_id)
);

CREATE TABLE IF NOT EXISTS custom_fields (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_field_id BIGINT UNIQUE,
    field_key TEXT NOT NULL UNIQUE,
    label TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ownership_custom_values (
    ownership_id BIGINT NOT NULL REFERENCES ownerships(id) ON DELETE CASCADE,
    field_id BIGINT NOT NULL REFERENCES custom_fields(id) ON DELETE CASCADE,
    value TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ownership_id, field_id)
);

ALTER TABLE attachments ADD COLUMN IF NOT EXISTS legacy_attachment_id BIGINT;
ALTER TABLE attachments ADD COLUMN IF NOT EXISTS ownership_id BIGINT REFERENCES ownerships(id) ON DELETE CASCADE;
ALTER TABLE attachments ADD COLUMN IF NOT EXISTS file_path TEXT;
ALTER TABLE attachments ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE attachments ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'external';
ALTER TABLE attachments ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1;
CREATE UNIQUE INDEX IF NOT EXISTS idx_attachments_legacy_attachment_id
ON attachments(legacy_attachment_id);
CREATE INDEX IF NOT EXISTS idx_attachments_ownership_id
ON attachments(ownership_id);

CREATE TABLE IF NOT EXISTS ownership_locations (
    ownership_id BIGINT PRIMARY KEY REFERENCES ownerships(id) ON DELETE CASCADE,
    latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90 AND 90),
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180 AND 180),
    source TEXT NOT NULL DEFAULT 'manual',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS duplicate_reviews (
    left_ownership_id BIGINT NOT NULL REFERENCES ownerships(id) ON DELETE CASCADE,
    right_ownership_id BIGINT NOT NULL REFERENCES ownerships(id) ON DELETE CASCADE,
    decision TEXT NOT NULL DEFAULT 'ignored',
    reviewed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (left_ownership_id, right_ownership_id),
    CHECK (left_ownership_id < right_ownership_id)
);

CREATE TABLE IF NOT EXISTS record_change_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_change_log_id BIGINT UNIQUE,
    ownership_id BIGINT NOT NULL REFERENCES ownerships(id) ON DELETE CASCADE,
    action_type TEXT NOT NULL,
    field_key TEXT NOT NULL,
    field_label TEXT NOT NULL,
    old_value TEXT,
    new_value TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS text_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_template_id BIGINT UNIQUE,
    template_type TEXT NOT NULL DEFAULT 'note',
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS recycle_bin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_recycle_id BIGINT UNIQUE,
    entity_type TEXT NOT NULL DEFAULT 'customer',
    original_id BIGINT,
    display_label TEXT,
    payload_json JSONB NOT NULL,
    deleted_by TEXT,
    deleted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS undo_operations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_undo_id BIGINT UNIQUE,
    operation_type TEXT NOT NULL,
    summary TEXT NOT NULL,
    payload_json JSONB NOT NULL,
    actor_username TEXT,
    status TEXT NOT NULL DEFAULT 'available',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    undone_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_notification_id BIGINT UNIQUE,
    notification_key TEXT NOT NULL UNIQUE,
    category TEXT NOT NULL,
    title TEXT NOT NULL,
    detail TEXT,
    severity TEXT NOT NULL DEFAULT '提醒',
    related_type TEXT,
    related_id BIGINT,
    legacy_related_id BIGINT,
    read_at TIMESTAMPTZ,
    dismissed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS import_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_profile_id BIGINT UNIQUE,
    name TEXT NOT NULL UNIQUE,
    mapping_json JSONB NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS report_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_report_template_id BIGINT UNIQUE,
    name TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    fields_json JSONB NOT NULL,
    header_text TEXT,
    footer_text TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS watchlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_watchlist_id BIGINT UNIQUE,
    name TEXT NOT NULL,
    normalized_name TEXT NOT NULL UNIQUE,
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS operation_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_operation_log_id BIGINT UNIQUE,
    action_type TEXT NOT NULL,
    summary TEXT NOT NULL,
    detail TEXT,
    actor_username TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO schema_migrations (version, name)
VALUES (2, 'desktop productivity mirror and complete parallel migration')
ON CONFLICT (version) DO NOTHING;

-- Version 3: server-owned offsite backup destinations.  Unlike desktop UI
-- preferences, these paths are resolved on the home server and shared by all
-- administrator clients.

CREATE TABLE IF NOT EXISTS server_backup_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    directory_path TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_success_at TIMESTAMPTZ,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO schema_migrations (version, name)
VALUES (3, 'server backup targets and remote maintenance')
ON CONFLICT (version) DO NOTHING;

-- Version 4: repaired identity cursors for databases restored or migrated from
-- an older package.  A stale cursor can make the first new history row collide
-- with an existing primary key and surface as a generic API 500.

SELECT setval(
    pg_get_serial_sequence('record_change_logs', 'id'),
    COALESCE(MAX(id), 1),
    MAX(id) IS NOT NULL
)
FROM record_change_logs;

SELECT setval(
    pg_get_serial_sequence('operation_logs', 'id'),
    COALESCE(MAX(id), 1),
    MAX(id) IS NOT NULL
)
FROM operation_logs;

INSERT INTO schema_migrations (version, name)
VALUES (4, 'repair history and operation log identity cursors')
ON CONFLICT (version) DO NOTHING;

-- Version 5: the server now verifies every identity-backed table at startup.
-- The actual cursor repair is performed by customer_api/postgres_schema.py so
-- it can preserve a sequence that is already ahead of MAX(id).

INSERT INTO schema_migrations (version, name)
VALUES (5, 'repair all PostgreSQL identity cursors')
ON CONFLICT (version) DO NOTHING;

-- Version 6: owner values shown on an ownership row are independent snapshots.
-- A normalized owner can be linked to more than one ownership.  Editing one
-- flat desktop row must not silently change the name, identity or address shown
-- on another row, even when both rows belong to the same parcel.

ALTER TABLE ownerships ADD COLUMN IF NOT EXISTS owner_name_override TEXT;
ALTER TABLE ownerships ADD COLUMN IF NOT EXISTS external_id_override TEXT;
ALTER TABLE ownerships ADD COLUMN IF NOT EXISTS address_override TEXT;

UPDATE ownerships ownership
SET owner_name_override = COALESCE(ownership.owner_name_override, owner.owner_name),
    external_id_override = COALESCE(ownership.external_id_override, owner.external_id),
    address_override = COALESCE(ownership.address_override, owner.address)
FROM owners owner
WHERE owner.id = ownership.owner_id
  AND (
      ownership.owner_name_override IS NULL
      OR ownership.external_id_override IS NULL
      OR ownership.address_override IS NULL
  );

INSERT INTO schema_migrations (version, name)
VALUES (6, 'ownership-specific owner display values')
ON CONFLICT (version) DO NOTHING;

-- Version 7: user-maintained attachment categories support the mobile gallery
-- without changing existing file paths, hashes, or backup behavior.

ALTER TABLE attachments ADD COLUMN IF NOT EXISTS category TEXT;

INSERT INTO schema_migrations (version, name)
VALUES (7, 'mobile attachment categories and gallery metadata')
ON CONFLICT (version) DO NOTHING;

-- Version 8: additive mobile field-visit planning.
--
-- Existing owners, lands, ownerships, contact logs and attachments remain the
-- source of truth.  The new tables only describe a dated route and its status
-- history, so desktop v1.8.x clients can continue to use the old API and
-- columns without knowing about field visits.

ALTER TABLE ownership_locations
ADD COLUMN IF NOT EXISTS geocode_status TEXT NOT NULL DEFAULT 'manual'
CHECK (geocode_status IN ('pending', 'success', 'failed', 'manual', 'not_required'));

ALTER TABLE ownership_locations
ADD COLUMN IF NOT EXISTS geocode_source TEXT;

ALTER TABLE ownership_locations
ADD COLUMN IF NOT EXISTS geocoded_at TIMESTAMPTZ;

ALTER TABLE ownership_locations
ADD COLUMN IF NOT EXISTS geocode_error TEXT;

ALTER TABLE ownership_locations
ADD COLUMN IF NOT EXISTS address_fingerprint TEXT;

UPDATE ownership_locations
SET geocode_status = CASE
        WHEN LOWER(COALESCE(source, 'manual')) = 'manual' THEN 'manual'
        ELSE 'success'
    END,
    geocode_source = COALESCE(NULLIF(geocode_source, ''), source),
    geocoded_at = COALESCE(geocoded_at, updated_at)
WHERE geocode_source IS NULL
   OR geocoded_at IS NULL;

CREATE TABLE IF NOT EXISTS field_visit_routes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_date DATE NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    title TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'planned'
        CHECK (status IN ('draft', 'planned', 'in_progress', 'completed', 'cancelled')),
    start_latitude DOUBLE PRECISION
        CHECK (start_latitude BETWEEN -90 AND 90),
    start_longitude DOUBLE PRECISION
        CHECK (start_longitude BETWEEN -180 AND 180),
    total_distance_km NUMERIC(14, 3)
        CHECK (total_distance_km IS NULL OR total_distance_km >= 0),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (
        (start_latitude IS NULL AND start_longitude IS NULL)
        OR
        (start_latitude IS NOT NULL AND start_longitude IS NOT NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_field_visit_routes_user_date_active
ON field_visit_routes(user_id, visit_date)
WHERE status <> 'cancelled';

CREATE INDEX IF NOT EXISTS idx_field_visit_routes_visit_date_user
ON field_visit_routes(visit_date, user_id);

CREATE TABLE IF NOT EXISTS field_visit_route_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_id BIGINT NOT NULL REFERENCES field_visit_routes(id) ON DELETE CASCADE,
    owner_id BIGINT NOT NULL REFERENCES owners(id) ON DELETE RESTRICT,
    ownership_id BIGINT NOT NULL REFERENCES ownerships(id) ON DELETE RESTRICT,
    land_id BIGINT NOT NULL REFERENCES lands(id) ON DELETE RESTRICT,
    route_order INTEGER NOT NULL CHECK (route_order > 0),
    status TEXT NOT NULL DEFAULT 'planned'
        CHECK (status IN (
            'planned', 'in_progress', 'completed', 'skipped', 'postponed', 'cancelled'
        )),
    priority INTEGER NOT NULL DEFAULT 0,
    is_order_locked BOOLEAN NOT NULL DEFAULT FALSE,
    estimated_distance_km NUMERIC(14, 3)
        CHECK (estimated_distance_km IS NULL OR estimated_distance_km >= 0),
    arrived_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    postponed_until TIMESTAMPTZ,
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_field_visit_route_items_ownership
        UNIQUE (route_id, ownership_id),
    CONSTRAINT uq_field_visit_route_items_order
        UNIQUE (route_id, route_order) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_field_visit_route_items_route_order
ON field_visit_route_items(route_id, route_order);

CREATE INDEX IF NOT EXISTS idx_field_visit_route_items_status
ON field_visit_route_items(status);

CREATE INDEX IF NOT EXISTS idx_field_visit_route_items_owner
ON field_visit_route_items(owner_id);

CREATE INDEX IF NOT EXISTS idx_field_visit_route_items_ownership
ON field_visit_route_items(ownership_id);

CREATE TABLE IF NOT EXISTS field_visit_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_item_id BIGINT NOT NULL
        REFERENCES field_visit_route_items(id) ON DELETE CASCADE,
    old_status TEXT
        CHECK (
            old_status IS NULL
            OR old_status IN (
                'planned', 'in_progress', 'completed',
                'skipped', 'postponed', 'cancelled'
            )
        ),
    new_status TEXT NOT NULL
        CHECK (new_status IN (
            'planned', 'in_progress', 'completed',
            'skipped', 'postponed', 'cancelled'
        )),
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    latitude DOUBLE PRECISION CHECK (latitude BETWEEN -90 AND 90),
    longitude DOUBLE PRECISION CHECK (longitude BETWEEN -180 AND 180),
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (
        (latitude IS NULL AND longitude IS NULL)
        OR
        (latitude IS NOT NULL AND longitude IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_field_visit_status_history_item_created
ON field_visit_status_history(route_item_id, created_at DESC, id DESC);

-- Idempotency results are server-side and short lived.  No customer data is
-- duplicated here; the response is reused only when the same user retries the
-- same write with the same key and request hash.
CREATE TABLE IF NOT EXISTS field_visit_idempotency_keys (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    idempotency_key TEXT NOT NULL,
    request_hash TEXT NOT NULL,
    response_json JSONB NOT NULL,
    status_code INTEGER NOT NULL CHECK (status_code BETWEEN 200 AND 599),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (user_id, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_field_visit_idempotency_expires
ON field_visit_idempotency_keys(expires_at);

-- Existing visit logs and attachments remain readable by desktop v1.8.x.
-- These nullable foreign keys only add optional field-visit context.
ALTER TABLE contact_logs
ADD COLUMN IF NOT EXISTS contacted_at TIMESTAMPTZ;

ALTER TABLE contact_logs
ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION
CHECK (latitude BETWEEN -90 AND 90);

ALTER TABLE contact_logs
ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION
CHECK (longitude BETWEEN -180 AND 180);

ALTER TABLE contact_logs
ADD COLUMN IF NOT EXISTS field_visit_route_item_id BIGINT
REFERENCES field_visit_route_items(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_contact_logs_field_visit_item
ON contact_logs(field_visit_route_item_id);

ALTER TABLE attachments
ADD COLUMN IF NOT EXISTS contact_log_id BIGINT
REFERENCES contact_logs(id) ON DELETE SET NULL;

ALTER TABLE attachments
ADD COLUMN IF NOT EXISTS field_visit_route_item_id BIGINT
REFERENCES field_visit_route_items(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_attachments_contact_log
ON attachments(contact_log_id);

CREATE INDEX IF NOT EXISTS idx_attachments_field_visit_item
ON attachments(field_visit_route_item_id);

INSERT INTO schema_migrations (version, name)
VALUES (8, 'mobile field visit routes status history and geocode metadata')
ON CONFLICT (version) DO NOTHING;
