-- LAND CUSTOMER SYSTEM v2 SCHEMA DRAFT
-- DRAFT ONLY. DO NOT EXECUTE AGAINST ANY DATABASE.
-- The guard intentionally aborts the transaction if this file is run.

BEGIN;
DO $$
BEGIN
    RAISE EXCEPTION 'V2 schema draft only; convert each section into a reviewed migration first.';
END
$$;

-- Current production PostgreSQL schema version: 7.
-- Proposed product v2 migrations: schema versions 8 through 12.

-- ---------------------------------------------------------------------------
-- Version 8: optimistic locking and actor metadata
-- ---------------------------------------------------------------------------

ALTER TABLE owners ADD COLUMN IF NOT EXISTS row_version BIGINT NOT NULL DEFAULT 1;
ALTER TABLE owners ADD COLUMN IF NOT EXISTS updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE lands ADD COLUMN IF NOT EXISTS row_version BIGINT NOT NULL DEFAULT 1;
ALTER TABLE lands ADD COLUMN IF NOT EXISTS updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE ownerships ADD COLUMN IF NOT EXISTS row_version BIGINT NOT NULL DEFAULT 1;
ALTER TABLE ownerships ADD COLUMN IF NOT EXISTS updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS row_version BIGINT NOT NULL DEFAULT 1;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE project_tasks ADD COLUMN IF NOT EXISTS row_version BIGINT NOT NULL DEFAULT 1;
ALTER TABLE project_tasks ADD COLUMN IF NOT EXISTS updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE follow_up_reminders ADD COLUMN IF NOT EXISTS row_version BIGINT NOT NULL DEFAULT 1;
ALTER TABLE follow_up_reminders ADD COLUMN IF NOT EXISTS updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE attachments ADD COLUMN IF NOT EXISTS row_version BIGINT NOT NULL DEFAULT 1;
ALTER TABLE attachments ADD COLUMN IF NOT EXISTS updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_ownerships_updated_at_id
ON ownerships(updated_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_projects_updated_at_id
ON projects(updated_at DESC, id DESC);

-- Version changes must be performed by repository UPDATE statements such as:
-- UPDATE ownerships
-- SET ..., row_version = row_version + 1, updated_at = CURRENT_TIMESTAMP,
--     updated_by = :actor_id
-- WHERE id = :id AND row_version = :expected_version;
-- A zero row count maps to HTTP 409 LCS_CONFLICT.

-- ---------------------------------------------------------------------------
-- Version 9: versioned project workflow
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS workflow_definitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_key TEXT NOT NULL,
    version INTEGER NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    active BOOLEAN NOT NULL DEFAULT FALSE,
    created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (workflow_key, version)
);

CREATE TABLE IF NOT EXISTS workflow_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id BIGINT NOT NULL REFERENCES workflow_definitions(id) ON DELETE CASCADE,
    state_key TEXT NOT NULL,
    label TEXT NOT NULL,
    position INTEGER NOT NULL DEFAULT 0,
    terminal BOOLEAN NOT NULL DEFAULT FALSE,
    color TEXT,
    UNIQUE (workflow_id, state_key)
);

CREATE TABLE IF NOT EXISTS workflow_transitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id BIGINT NOT NULL REFERENCES workflow_definitions(id) ON DELETE CASCADE,
    from_state_id BIGINT NOT NULL REFERENCES workflow_states(id) ON DELETE CASCADE,
    to_state_id BIGINT NOT NULL REFERENCES workflow_states(id) ON DELETE CASCADE,
    label TEXT NOT NULL,
    required_role TEXT,
    require_note BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (workflow_id, from_state_id, to_state_id)
);

CREATE TABLE IF NOT EXISTS project_workflow_instances (
    project_id BIGINT PRIMARY KEY REFERENCES projects(id) ON DELETE CASCADE,
    workflow_id BIGINT NOT NULL REFERENCES workflow_definitions(id) ON DELETE RESTRICT,
    state_id BIGINT NOT NULL REFERENCES workflow_states(id) ON DELETE RESTRICT,
    row_version BIGINT NOT NULL DEFAULT 1,
    updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS project_workflow_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    workflow_id BIGINT NOT NULL REFERENCES workflow_definitions(id) ON DELETE RESTRICT,
    from_state_id BIGINT REFERENCES workflow_states(id) ON DELETE SET NULL,
    to_state_id BIGINT NOT NULL REFERENCES workflow_states(id) ON DELETE RESTRICT,
    actor_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ---------------------------------------------------------------------------
-- Version 10: notification delivery and cross-client receipts
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS notification_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id BIGINT NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,
    recipient_type TEXT NOT NULL CHECK (recipient_type IN ('user', 'line_principal')),
    recipient_key TEXT NOT NULL,
    channel TEXT NOT NULL CHECK (channel IN ('desktop', 'mobile', 'line')),
    delivery_status TEXT NOT NULL DEFAULT 'pending',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    error_code TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (notification_id, recipient_type, recipient_key, channel)
);

CREATE TABLE IF NOT EXISTS notification_receipts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id BIGINT NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,
    recipient_type TEXT NOT NULL CHECK (recipient_type IN ('user', 'line_principal')),
    recipient_key TEXT NOT NULL,
    receipt_type TEXT NOT NULL CHECK (receipt_type IN ('read', 'dismissed', 'completed')),
    actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    client_type TEXT NOT NULL CHECK (client_type IN ('desktop', 'mobile', 'line')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (notification_id, recipient_type, recipient_key, receipt_type)
);

-- recipient_key for LINE is an opaque integration principal key, never a raw
-- LINE User ID. The LINE Bot keeps its binding database and resolves the key.

-- ---------------------------------------------------------------------------
-- Version 11: background jobs, integrity scans, audit query and data scopes
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS background_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_key TEXT NOT NULL UNIQUE,
    job_type TEXT NOT NULL,
    schedule_text TEXT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    settings_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS job_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES background_jobs(id) ON DELETE CASCADE,
    status TEXT NOT NULL CHECK (status IN ('running', 'succeeded', 'failed', 'cancelled')),
    attempt INTEGER NOT NULL DEFAULT 1,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMPTZ,
    summary_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    error_code TEXT,
    request_id TEXT
);

CREATE TABLE IF NOT EXISTS attachment_integrity_scans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attachment_id BIGINT NOT NULL REFERENCES attachments(id) ON DELETE CASCADE,
    expected_sha256 TEXT,
    actual_sha256 TEXT,
    status TEXT NOT NULL CHECK (status IN ('ok', 'missing', 'mismatch', 'unreadable')),
    scanned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    job_run_id BIGINT REFERENCES job_runs(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS api_request_audits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id TEXT NOT NULL UNIQUE,
    actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    client_type TEXT NOT NULL,
    action_type TEXT NOT NULL,
    entity_type TEXT,
    entity_id BIGINT,
    result TEXT NOT NULL,
    status_code INTEGER NOT NULL,
    duration_ms INTEGER NOT NULL,
    error_code TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_api_request_audits_created
ON api_request_audits(created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_api_request_audits_action_result
ON api_request_audits(action_type, result, created_at DESC);

CREATE TABLE IF NOT EXISTS user_permissions (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    permission_key TEXT NOT NULL,
    allowed BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, permission_key)
);

CREATE TABLE IF NOT EXISTS user_data_scopes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    scope_type TEXT NOT NULL CHECK (scope_type IN ('district', 'section', 'project')),
    scope_value TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, scope_type, scope_value)
);

-- api_request_audits must never contain request bodies, Authorization headers,
-- identity values, addresses, notes, query text, passwords, DSNs or file data.

-- ---------------------------------------------------------------------------
-- Version 12: upgrade, validation and rollback evidence
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS upgrade_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upgrade_key TEXT NOT NULL UNIQUE,
    from_server_version TEXT NOT NULL,
    to_server_version TEXT NOT NULL,
    from_schema_version INTEGER NOT NULL,
    to_schema_version INTEGER NOT NULL,
    status TEXT NOT NULL,
    backup_name TEXT,
    backup_sha256 TEXT,
    started_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMPTZ,
    rollback_at TIMESTAMPTZ,
    summary_json JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS upgrade_checks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upgrade_batch_id BIGINT NOT NULL REFERENCES upgrade_batches(id) ON DELETE CASCADE,
    stage TEXT NOT NULL,
    check_key TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('passed', 'failed', 'warning', 'skipped')),
    expected_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    actual_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    error_code TEXT,
    checked_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (upgrade_batch_id, stage, check_key)
);

-- Each real migration will insert exactly one schema_migrations row only after
-- its transaction and post-checks have succeeded.
-- VALUES (8, 'optimistic locking and actor metadata')
-- VALUES (9, 'versioned project workflow')
-- VALUES (10, 'notification delivery and receipts')
-- VALUES (11, 'jobs integrity audit and data scopes')
-- VALUES (12, 'upgrade validation and rollback evidence')

ROLLBACK;
